version: '3.7'

networks:
  psql_test:

services:

  db:
    build:
      context: .docker-containers/postgres
    restart: "on-failure"
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .docker-env/dev/postgres.env
    environment:
      - POSTGRES_DB_USER=docker
    ports:
      - "5435:5432"
    ulimits:
      nproc: 128000
      nofile:
        soft: 50000
        hard: 120000
    networks:
      - psql_test

volumes:
  db:
