"""Init migration

Revision ID: 669014d67de3
Revises: 
Create Date: 2021-08-27 08:40:28.223971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669014d67de3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('origin_doc_link', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('fields_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
